--------------------------- MODULE CalibrationFramework ---------------------------
(*****************************************************************************)
(* PLACEHOLDER. Bound by PHASE_CUDA_NATIVE_DISPATCH.md commit C0.            *)
(*                                                                            *)
(* Companion to specs/cuda-native-dispatch/calibrated_dispatch_framework    *)
(* .allium.                                                                  *)
(*                                                                            *)
(* Models the calibration framework as a state machine over the lifetime    *)
(* of a process:                                                             *)
(*                                                                            *)
(*     INIT → (CacheHit ⇒ READY) ∨ (CacheMiss ⇒ PROBING → CACHED → READY)   *)
(*                                                                            *)
(* The load-bearing invariants:                                              *)
(*                                                                            *)
(*   - ProbeIsDeterministicModuloQuantization: for a fixed hardware tuple,  *)
(*       Probe(op, size) returns latencies that quantize to the same bucket *)
(*       (in {0, 1MB, 10MB, 100MB, 1GB, SIZE_MAX}) across runs.             *)
(*   - CacheLoadIdempotent: WriteCache then ReadCache returns the SAME      *)
(*       threshold table.                                                    *)
(*   - ThresholdQuantized: ∀ op ∈ RegisteredOps: threshold[op] ∈            *)
(*       {0, 1MB, 10MB, 100MB, 1GB, SIZE_MAX}.                              *)
(*   - DispatchIsPureFunction: the strategy chosen at a calibrated op site *)
(*       is uniquely determined by (op_id, payload_bytes, threshold[op_id]).*)
(*   - CalibrationCompletesBeforeFirstDispatch: every dispatch query        *)
(*       happens after the framework reaches READY state.                   *)
(*                                                                            *)
(* The cache_key invalidates calibration when any of                       *)
(* (gpu_uuid, cuda_version, ggml_version) changes. Modeled as a CONSTANT  *)
(* triple; mismatch transitions cache state from CACHED back to PROBING.   *)
(*                                                                            *)
(* CODE REFS (post-C0):                                                     *)
(*   ik_llama.cpp/ggml/src/ggml-cuda/calibration.h                         *)
(*   ik_llama.cpp/ggml/src/ggml-cuda/calibration.cu                        *)
(*   ~/.cache/ggml/cuda-calibration-{key}.json                             *)
(*                                                                            *)
(* TBD: fill VARIABLES, Init, Next, invariants when C0 lands.               *)
(*****************************************************************************)

EXTENDS Naturals, Sequences, FiniteSets

(* TBD: CONSTANTS for registered ops, quantization buckets, cache_key      *)
(*      tuple. *)

(* TBD: VARIABLES for framework state, threshold table, cache file        *)
(*      contents, probe history.                                           *)

(* TBD: Init *)

(* TBD: Next (CacheCheck, Probe, Quantize, WriteCache, ReadCache,         *)
(*      Dispatch transitions) *)

(* TBD: invariants                                                         *)
(*    ProbeIsDeterministicModuloQuantization                              *)
(*    CacheLoadIdempotent                                                 *)
(*    ThresholdQuantized                                                  *)
(*    DispatchIsPureFunction                                              *)
(*    CalibrationCompletesBeforeFirstDispatch                             *)

============================================================================
