--------------------------- MODULE CalibratedOpEquivalence ---------------------------
(*****************************************************************************)
(* PLACEHOLDER. Bound by PHASE_CUDA_NATIVE_DISPATCH.md commits C8, C9,      *)
(* C10, C11. Model-checking runs once after all four ops are registered     *)
(* (end of C11).                                                             *)
(*                                                                            *)
(* Companion to specs/cuda-native-dispatch/calibrated_op_equivalence       *)
(* .allium.                                                                  *)
(*                                                                            *)
(* Models each calibrated op as a 2-strategy choice (default vs alt). For  *)
(* a fixed input, both strategies produce equivalent output under that    *)
(* op's documented criterion (byte-identical OR fp16/fp32 ULP-bound).      *)
(*                                                                            *)
(* The load-bearing invariant:                                               *)
(*                                                                            *)
(*   - OutputDoesNotDependOnStrategy: for every registered op and every    *)
(*       payload, both strategies' outputs satisfy the op's equivalence    *)
(*       predicate. The dispatch decision (which strategy fires) may       *)
(*       differ across hardware via calibration, but the output bits must  *)
(*       satisfy the predicate regardless of which fires.                  *)
(*                                                                            *)
(* Per-op equivalence predicates (modelled abstractly):                    *)
(*                                                                            *)
(*   REDUCE_CROSS_DEVICE:                                                  *)
(*     ByteIdentical(default_out, alt_out)                                 *)
(*     (PD5 confirmed across 13 measured shapes from 2 MB to 1.5 GB)       *)
(*                                                                            *)
(*   MATMUL_STREAM_SPLIT:                                                  *)
(*     Fp16UlpBound(default_out, alt_out, 1)                               *)
(*     (cuBLAS K-tile config may shift the reduction tree; equivalence is *)
(*      within 1 ULP at fp16 precision, ~0.02% relative error)              *)
(*                                                                            *)
(*   PEER_COPY:                                                            *)
(*     ByteIdentical(default_out, alt_out)                                 *)
(*     (Both paths are byte-preserving; no arithmetic)                     *)
(*                                                                            *)
(*   GRAPH_CAPTURE:                                                        *)
(*     ByteIdentical(default_out, alt_out)                                 *)
(*     (Same kernel sequence, different dispatch — captured replay vs     *)
(*      eager launch — produce identical computation)                       *)
(*                                                                            *)
(* The negative variant removes one op's equivalence and checks that      *)
(* the dispatch becomes observable in TLC's state space — confirms the    *)
(* contract is load-bearing.                                                *)
(*                                                                            *)
(* CODE REFS (post-implementation):                                         *)
(*   C8: ik_llama.cpp/ggml/src/ggml-cuda.cu mul_mat dispatch              *)
(*   C9: ik_llama.cpp/ggml/src/ggml-cuda/reduce.cu                        *)
(*   C10: ik_llama.cpp/ggml/src/ggml-cuda.cu cpy_tensor_async              *)
(*   C11: ik_llama.cpp/ggml/src/ggml-cuda.cu graph_compute                 *)
(*                                                                            *)
(* TBD: fill VARIABLES, Init, Next, invariant when C8-C11 land.            *)
(*****************************************************************************)

EXTENDS Naturals, Sequences, FiniteSets

(* TBD: CONSTANTS for registered op set, abstract input/output values,     *)
(*      ULP bounds per op. *)

(* TBD: VARIABLES per-op default_out, alt_out for the current modelled    *)
(*      input. *)

(* TBD: Init (set up the four registered ops with their default/alt       *)
(*      strategy specs) *)

(* TBD: Next (Execute op under either strategy; record output) *)

(* TBD: invariant                                                          *)
(*    OutputDoesNotDependOnStrategy(op):                                  *)
(*      EquivPredicate[op](default_out[op], alt_out[op])                  *)

============================================================================
