#!/usr/bin/env bash
#
# verify_projection.sh — portable runner for the PHASE25 cross-uarch
# projection table. Runs bench-turbo-kv-quantize on the current host
# and reports the AVX2 quantize ns/call alongside the projected value
# for that target, so teammates with access to Haswell / Alder Lake /
# Raptor Lake / Zen 1 / Zen 3 silicon can confirm the Zen-2-extrapolated
# numbers.
#
# Projection source: reference/agner/per_uarch_projection.txt (committed),
# generated by analyze.py from the Agner Fog table.
#
# Usage:
#     ./verify_projection.sh                    # auto-detect uarch from /proc/cpuinfo
#     ./verify_projection.sh --uarch=Haswell    # override detection
#     ./verify_projection.sh --bench=<path>     # override bench binary
#
# Exit status: 0 = within ±20% of projection, 1 = measurement outside window
# (bench noise is typically ±10%; ±20% is a generous tolerance for
# different clock speeds / thermal / background load).

set -eu

# Projected values (ns/call) at Zen 2 baseline clock (~3.5 GHz boost).
# Updated when the projection changes.
declare -A PROJ=(
    [Haswell]=330
    [Skylake]=301
    [IceLake]=301
    [AlderLake]=301     # proxy = IceLake per README.md
    [RaptorLake]=301    # proxy = IceLake per README.md
    [Zen1]=434
    [ZenPlus]=434       # proxy = Zen 1
    [Zen2]=311
    [Zen3]=301
    [Zen4]=311          # Zen 4 is AVX-512 and routes to scalar fallback,
                        # so this cell is only meaningful if AVX-512 kernel
                        # is later added. Listed as identical to Zen 3 per
                        # Agner's numbers.
)

BENCH="${BENCH:-}"
UARCH_OVERRIDE=""

for arg in "$@"; do
    case "$arg" in
        --bench=*)  BENCH="${arg#*=}" ;;
        --uarch=*)  UARCH_OVERRIDE="${arg#*=}" ;;
        -h|--help)
            sed -n '2,23p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "unknown arg: $arg" >&2
            exit 2
            ;;
    esac
done

# --- Locate bench binary ---------------------------------------------------
if [[ -z "$BENCH" ]]; then
    # Common build-tree locations
    for path in \
        "llama.cpp/build-tq/bin/bench-turbo-kv-quantize" \
        "llama.cpp/build/bin/bench-turbo-kv-quantize" \
        "build-tq/bin/bench-turbo-kv-quantize" \
        "build/bin/bench-turbo-kv-quantize"; do
        if [[ -x "$path" ]]; then
            BENCH="$path"
            break
        fi
    done
fi
if [[ -z "$BENCH" || ! -x "$BENCH" ]]; then
    echo "error: bench-turbo-kv-quantize not found." >&2
    echo "Build it with:" >&2
    echo "  cmake --build <build-dir> --target bench-turbo-kv-quantize" >&2
    echo "and re-run with --bench=<path>." >&2
    exit 2
fi

# --- Detect microarchitecture ----------------------------------------------
detect_uarch() {
    local vendor family model
    vendor=$(grep -m1 '^vendor_id' /proc/cpuinfo | awk '{print $3}')
    family=$(grep -m1 '^cpu family' /proc/cpuinfo | awk -F: '{print $2+0}')
    model=$(grep -m1 '^model' /proc/cpuinfo | grep -v name | awk -F: '{print $2+0}')

    case "$vendor" in
        GenuineIntel)
            if [[ "$family" != "6" ]]; then
                echo "UnknownIntel"; return
            fi
            case "$model" in
                60|63|69|70)          echo "Haswell" ;;
                61|71|79|86)          echo "Broadwell" ;;     # projection = Haswell
                78|94)                echo "Skylake" ;;
                151|154)              echo "AlderLake" ;;
                183|186|190|191)      echo "RaptorLake" ;;
                85)                   echo "SkylakeX (AVX-512 — out of scope)" ;;
                125|126|140|141)      echo "IceLake" ;;       # client + SP
                167|173|175)          echo "TigerLake" ;;     # projection = IceLake
                *)                    echo "UnknownIntel($model)" ;;
            esac
            ;;
        AuthenticAMD)
            case "$family-$model" in
                23-1|23-17|23-32)     echo "Zen1" ;;
                23-8|23-24)           echo "ZenPlus" ;;
                23-49|23-71|23-96|23-104|23-113|23-160)   echo "Zen2" ;;
                25-0|25-1|25-8|25-33|25-80|25-81)         echo "Zen3" ;;
                25-16|25-17|25-24|25-96|25-97|25-112|25-113|25-116|25-160|25-161)
                                                          echo "Zen4 (AVX-512 — out of scope)" ;;
                *)                                        echo "UnknownAMD($family-$model)" ;;
            esac
            ;;
        *) echo "Unknown($vendor)" ;;
    esac
}

UARCH="${UARCH_OVERRIDE:-$(detect_uarch)}"

# --- Run bench 5 times, take median ----------------------------------------
echo "==> host: $(uname -m) / $(uname -r)"
echo "==> detected uarch: $UARCH"
echo "==> bench: $BENCH"
echo "==> running 5 iterations, reporting median..."
echo

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
for i in 1 2 3 4 5; do
    "$BENCH" 2>&1 | awk -F: '/AVX2/ { gsub(/[ ns\/call]+/, "", $2); print $2 }' >> "$tmp"
done

# Sort the 5 samples and pick the 3rd (median)
sorted=$(sort -g "$tmp")
median=$(echo "$sorted" | sed -n 3p)

echo "samples (ns/call): $(echo $sorted | tr '\n' ' ')"
echo "median: $median ns/call"

# --- Compare against projection --------------------------------------------
projected="${PROJ[$UARCH]:-}"
if [[ -z "$projected" ]]; then
    echo "no projection on file for uarch '$UARCH' — reporting median only"
    exit 0
fi

# Compute relative error
delta=$(awk -v m="$median" -v p="$projected" 'BEGIN { printf "%.1f", (m - p) * 100 / p }')
abs_delta=$(awk -v d="$delta" 'BEGIN { if (d < 0) d = -d; printf "%.1f", d }')

echo
echo "projection for $UARCH:   $projected ns/call"
echo "measured:                $median ns/call"
echo "delta vs projection:     $delta %"

# ±20% tolerance
tolerance=20
within=$(awk -v d="$abs_delta" -v t="$tolerance" 'BEGIN { print (d <= t) ? 1 : 0 }')
if [[ "$within" == "1" ]]; then
    echo "==> within ±${tolerance}% window — projection validated"
    exit 0
else
    echo "==> OUTSIDE ±${tolerance}% window — investigate" >&2
    echo "   - check CPU frequency scaling (cpupower frequency-info)" >&2
    echo "   - check thermal throttling (sensors)" >&2
    echo "   - check background load (top)" >&2
    echo "   - confirm the bench was built with -O3 -march=native" >&2
    exit 1
fi
